### ISSUE TITLE
'Licentie' / non-commercieel

### ISSUE THREAD

**Issue by twinaphex** [rmaz/ARMSNES-libretro#9]
Dutch
--------

Hallo daar,

ik zie dat je onze repo hebt 'geforked', en ik hoor van derden (waaronder KissKissBank en RetroPac) dat jij meent 'rechten' te kunnen verlenen aan twee universiteitskindjes die denken een startup te kunnen opzetten genaamd 'retroPac'. 

https://www.nostalgames.fr

Zij denken dat jij 'rechten' aan hun hebt verleend en daarom kunnen ze gebruik maken van deze software wat wel DEGELIJK 100% gebaseerd is op non-commercieel gelicenseerde software, en waar jij dus ook geen inbreuk aan kunt doen.

Als ze hierover gelogen hebben, laat het me dan a.u.b. weten. Als jij dit verhaal kunt bevestigen aan mij (dat jij dus inderdaad 'gratie' hebt verleent aan deze gasten), dan ben ik bereidt verdere stappen te ondernemen, om te beginnen om eens te gaan bellen met Uber en te vragen of ze dit soort gedrag op prijs stellen van hun werknemers, wazige sublicenties over 'eigendom' dat eigenlijk niet tot jou toebehoort. Het laatste wat jij gaat doen als het aan mij betreft is om 'businessdeals' te maken met een stelletje wazige ondernemers in Frankrijk terwijl de licenties van de emulator dit expres verbieden. In dat geval kun je dit goedmaken door explicit tegenover zowel Kiss Kiss Bank als Nostalgames te vermelden dat ze NIET jouw permissie hebben en ook niet KUNNEN hebben omdat jij namelijk niet alle rechten bezit over deze code, en ook nooit kan bezitten.

Ik hoop voor beide partijen dat dit een misverstand is, je hier niets van afweet, en dat de betreffende partijen die dit beweren hierover hebben gelogen. In ieder geval zou ik graag willen zien dat je Kiss Kiss Bank ervan op de hoogte stelt dat (ook al zou je willen) je niet bevoegd bent om zomaar rechten af te geven aan deze partij aangezien de code niet enkel door jou is geschreven en er meerdere copyright holders zijn over de code.

E-mail deze personen 

jean-samuel.kriegk@kisskissbankbank.com
adrien.aumont@kisskissbankbank.com

English
--------

Hi there,

I see that you have forked one of our repos, and I have heard from reliable third-party sources (including KissKissBank and RetroPac) that you seem to think you are able to sign over 'rights' and 'permission' to two fledgling university kids in France that have set up a startup company around retro emulation software, in specific this snes9x 2002 fork, 'ARMSNES-libretro'.

https://www.nostalgames.fr

They think that you are able to singlehandedly give away 'rights' so that they can use this software on their 'commercial for-profit' console which is obviously NOT AT ALL possible since the original base software has been licensed under a non-commercial license, which you cannot singlehandedly change on your own.

If they have lied about this, let me know and we can rectify this situation. If however they have not and you are willing to admit to these shenanigans, I am prepared to take further action. To begin with, I'd like to have your current employer on the phone (Uber) and see how they feel about their employees illegally doing subcontracting/licensing deals over work they don't own any rights to, shady wishywashy activity like that.

The last thing that is going to happen under my watch is for you to be making 'business deals' with a bunch of shady entrepreneurs in France over emulators that have expressly FORBIDDEN commercial usage. You have the chance to rectify this by contacting both Kiss Kiss Bank and Nostalgames yourself and telling them in no uncertain terms that YOU are not ABLE to give them licensing permissions to use this, you would have to seek out every member of the Snes9x project and get their permission first in order to do this.

Let this be a clear warning. I am not playing around here. I hope this is a huge misunderstanding, that you know nothing of this, and they lied. But in case they didn't, I insist that you e-mail them here - and let them know that it's NOT UP TO YOU to give them 'permission' to use this on their for-profit 'product', since there are multiple copyright holders over the code and the license explicitly prohibits commercial use.

E-mail these individuals and let them know -

jean-samuel.kriegk@kisskissbankbank.com
adrien.aumont@kisskissbankbank.com

**Comment by rmaz** [comment]
Hey guy(s). No need for the heavy handed approach here, this was just a hobby fork I was working on to squeeze a few more cycles out of a rpi1. I'm not aware of any french guys who are monetising this, and obviously have not given away any rights for this code as I do not own any. All licenses and copyrights in the code remain untouched.

I don't need this any more anyway, the catsfc core has much better support and is fast enough on an rpi2. I'll delete this if it will make your lives simpler.
